development:
  features:
    video_sidebar: true
    organizations_menu: true
    speakers_menu: true
production:
  features:
    video_sidebar: true
    organizations_menu: true
    speakers_menu: true
